# Generated by Django 5.0.7 on 2024-12-12 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('issue', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 7, 24, 2, 926616, tzinfo=datetime.timezone.utc)),
        ),
    ]
