# Generated by Django 5.0.7 on 2024-12-12 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_transactions_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 11, 53, 53, 170234, tzinfo=datetime.timezone.utc)),
        ),
    ]
