# Generated by Django 5.0.7 on 2024-12-12 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 11, 55, 51, 284376, tzinfo=datetime.timezone.utc)),
        ),
    ]
