# Generated by Django 5.0.7 on 2024-12-12 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiptent_no',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 11, 59, 11, 994579, tzinfo=datetime.timezone.utc)),
        ),
    ]
