# Generated by Django 5.0.7 on 2024-12-13 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_transactions_receiptent_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='receiptent_no',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 12, 28, 58, 589179, tzinfo=datetime.timezone.utc)),
        ),
    ]
