# Generated by Django 5.0.7 on 2024-12-13 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_alter_transactions_receiptent_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='DoB',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='Pan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='aadhaar',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='User/Images'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 12, 29, 21, 123227, tzinfo=datetime.timezone.utc)),
        ),
    ]
