# Generated by Django 5.0.7 on 2024-12-13 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_user_reg_dob_user_reg_pan_user_reg_aadhaar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='support',
            new_name='Supports',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 14, 2, 38, 207588, tzinfo=datetime.timezone.utc)),
        ),
    ]
