# Generated by Django 5.0.7 on 2024-12-13 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_rename_support_supports_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 14, 2, 57, 813013, tzinfo=datetime.timezone.utc)),
        ),
    ]
