# Generated by Django 5.0.7 on 2024-12-15 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_alter_transactions_timestamp_alter_user_reg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 13, 55, 43, 4639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='User/Images'),
        ),
    ]
